# Generated by Django 5.0.2 on 2024-02-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggs', '0002_tag_dog_vote_ratio_dog_vote_total_review_dog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
