# Generated by Django 5.0.2 on 2024-03-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggs', '0005_alter_dog_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name']},
        ),
    ]
